version: "3.3"

services:
  database:
    container_name: lme_flask
    image: postgres
    restart: always
    volumes:
    - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=lmeflask
      - POSTGRES_USER=lmeflask
    ports:
      - 5432:5432
